.

diff --git a/.github/workflows/node-deploy-ssh.yml b/.github/workflows/node-deploy-ssh.yml
--- a/.github/workflows/node-deploy-ssh.yml
+++ b/.github/workflows/node-deploy-ssh.yml
@@ -1,6 +1,3 @@
-# This workflow will do a clean install of node dependencies, build the source code, and run tests across different versions of node
-# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
-
 name: Deploy Node Application
 
 on:
@@ -24,13 +21,17 @@ on:
       EXECUTE_DEPLOYMENT:
         required: false
         type: boolean
+      REDEPLOY:
+        required: false
+        type: boolean
       BUILD_DIR_NAME:
         required: false
         type: string
         default: "build"
-    secrets:
       SSH_HOST:
         required: true
+        type: string
+    secrets:
       SSH_KEY:
         required: true
       SSH_USER:
@@ -44,7 +45,6 @@ jobs:
     strategy:
       matrix:
         node-version: [18.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
       - uses: actions/checkout@v2
@@ -52,7 +52,7 @@ jobs:
           persist-credentials: false
 
       - name: Pull Env file from Config
-        if: ${{ inputs.ENV_FILE_PATH != '' }}
+        if: ${{ inputs.ENV_FILE_PATH != '' && inputs.REDEPLOY != true }}
         run: |
           GH_TOKEN=$GH_TOKEN
           FILE_URL="https://api.github.com/repos/${{ github.repository_owner }}${{ inputs.ENV_FILE_PATH }}"
@@ -71,50 +71,41 @@ jobs:
         uses: actions/setup-node@v1
         with:
           node-version: ${{ matrix.node-version }}
-          
+
       - name: Export GH Token
         if: ${{ secrets.GH_TOKEN != '' }}
         run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
 
-#      - name: Cache Node.js modules
-#        uses: actions/cache@v2
-#        with:
-#          # npm cache files are stored in `~/.npm` on Linux/macOS
-#          path: ~/.npm
-#          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
-#          restore-keys: |
-#            ${{ runner.OS }}-node-
-#            ${{ runner.OS }}-
-
       - name: Install dependencies
+        if: ${{ inputs.REDEPLOY != true }}
         run: npm install --frozen-lockfile
 
       - name: Run the tests
-        if: ${{ inputs.RUN_TESTS == true }}
-        run:  npm run test
+        if: ${{ inputs.RUN_TESTS == true && inputs.REDEPLOY != true }}
+        run: npm run test
 
       - name: Build
-        if: ${{ inputs.EXECUTE_DEPLOYMENT == true }}
+        if: ${{ inputs.EXECUTE_DEPLOYMENT == true && inputs.REDEPLOY != true }}
         run: CI=false npm run build
 
       - name: Compress build directory
-        if: ${{ inputs.EXECUTE_DEPLOYMENT == true }}
+        if: ${{ inputs.EXECUTE_DEPLOYMENT == true && inputs.REDEPLOY != true }}
         run: tar -czf nodejs-build-${{ inputs.NAME }}.${{ github.run_number }}.tar.gz ${{ inputs.BUILD_DIR_NAME }}
 
       - name: Copy artifact to server
-        if: ${{ inputs.EXECUTE_DEPLOYMENT == true }}
+        if: ${{ inputs.EXECUTE_DEPLOYMENT == true && inputs.REDEPLOY != true }}
         run: |
           echo "${{ secrets.SSH_KEY }}" > /tmp/deploy_key
           chmod 600 /tmp/deploy_key
           ls -lrth
-          scp -o StrictHostKeyChecking=no -i /tmp/deploy_key nodejs-build-${{ inputs.NAME }}.${{ github.run_number }}.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp
+          scp -o StrictHostKeyChecking=no -i /tmp/deploy_key nodejs-build-${{ inputs.NAME }}.${{ github.run_number }}.tar.gz ${{ secrets.SSH_USER }}@${{ inputs.SSH_HOST }}:/tmp
           rm /tmp/deploy_key
 
       - name: Extract artifact, run migration, test and restart
-        if: ${{ inputs.EXECUTE_DEPLOYMENT == true }}
+        if: ${{ inputs.EXECUTE_DEPLOYMENT == true && inputs.REDEPLOY != true }}
         uses: appleboy/ssh-action@master
         with:
-          host: ${{ secrets.SSH_HOST }}
+          host: ${{ inputs.SSH_HOST }}
           key: ${{ secrets.SSH_KEY }}
           username: ${{ secrets.SSH_USER }}
           script: |
@@ -131,7 +122,6 @@ jobs:
                 exit 1
               fi
               wget "$DOWNLOAD_URL" -O "tmp.env" || { echo "Error: Failed to download env file." >&2; exit 1; }
-            
               mkdir -p env-bk
               mv .env env-bk/.env-$(date +"%Y-%m-%d-%H-%M-%S")
               mv tmp.env .env
@@ -143,4 +133,28 @@ jobs:
               npm run test
             fi
             tar -xzf /tmp/nodejs-build-${{ inputs.NAME }}.${{ github.run_number }}.tar.gz -C .
+            npm run deploy
+
+      - name: Refresh .env and redeploy
+        if: ${{ inputs.REDEPLOY == true }}
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ inputs.SSH_HOST }}
+          key: ${{ secrets.SSH_KEY }}
+          username: ${{ secrets.SSH_USER }}
+          script: |
+            git config --global --add safe.directory ${{ inputs.PROJECT_PATH }}
+            cd ${{ inputs.PROJECT_PATH }}
+            if [[ -n "${{ inputs.ENV_FILE_PATH }}" ]]; then
+              FILE_URL="https://api.github.com/repos/${{ github.repository_owner }}${{ inputs.ENV_FILE_PATH }}"
+              DOWNLOAD_URL=$(curl -sH "Authorization: token ${{ secrets.GH_TOKEN }}" "$FILE_URL" | grep -oP '(?<="download_url": ")[^"]+')
+              if [[ -z "$DOWNLOAD_URL" ]]; then
+                echo "Error: Failed to fetch env file download URL for the file." >&2
+                exit 1
+              fi
+              wget "$DOWNLOAD_URL" -O "tmp.env" || { echo "Error: Failed to download env file." >&2; exit 1; }
+              mkdir -p env-bk
+              mv .env env-bk/.env-$(date +"%Y-%m-%d-%H-%M-%S")
+              mv tmp.env .env
+            fi
             npm run deploy
